pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  azureSub: 'castiglione@gmail.com'
  azureApp: 'card-game'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    nobuild: true
    projects: 'Cardgame/Cardgame.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  inputs:
    azureSubscription: $(azureSub)
    appName: $(azureApp)
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
    slotName: test

- task: AzureWebApp@1
  condition: eq(variables['build.sourceBranch'], 'refs/heads/release')
  inputs:
    azureSubscription: $(azureSub)
    appName: $(azureApp)
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
    slotName: production